spring.application.name=image-translator

# Spring AI Configuration
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-3.5-turbo

# Tesseract Configuration (Update this path based on your OS)
# Mac Homebrew example: /opt/homebrew/share/tessdata
# Windows example: C:/Program Files/Tesseract-OCR/tessdata
tesseract.datapath=/opt/homebrew/share/tessdata